import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";

import Providers from "./_common/components/Providers";
import RootLayoutHeader from "./_common/components/LayoutHeader";

import "./globals.css";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<Readonly<RootLayoutProps>> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`antialiased ${pretendard.variable}`}>
        <div className="w-full h-full">
          <Providers>
            <RootLayoutHeader />
            <main className="w-full min-h-[calc(100%-3.5rem)]">{children}</main>
          </Providers>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
